# 6. Error

### Error and Exceptions

#### 문법 에러 (Syntax Error)

가장 많이 볼 수 있는 에러로 발생한 파일 이름과 줄번호, `^` 문자를 통해 파이썬이 읽어 들일 때(parser)의 문제 발생 위치를 표현한다.

`parser` 는 문제가 되는 줄을 다시 보여주고 줄에서 에러가 감지된 가장 앞의 위치를 가리키는 작은 화살표 `^`로 표시된다.

#### 예외 (Exceptions)

문법이나 표현식이 바르게 되어있지만 실행시 발생하는 에러다.

- `ZeroDivisionError` : 0으로 나눌 수 없기에 발생

- `NameError` : 지역 혹은 전역 이름 공간 내에서 유효하지 않는 이름(정의되지 않은 변수)를 호출할 경우 발생

- `TypeError` : 자료형에 대한 타입 자체가 잘못된 경우 발생, 함수 호출과정에서도 발생 가능

- `ValueError` : 자료형에 대한 타입은 올바르나 값이 적절하지 않은 경우 발생

- `IndexError` : list index out of range

- `KeyError` : 딕셔너리에 Key가 없는 경우 발생

- `ModuleNotFoundError` : 모듈을 찾을 수 없는 경우 발생

- `ImportError` : 모듈을 찾았지만 가져오는 과정에서 실패하는 경우 발생

- `KeyboardInterrupt` 

  ```python
  while True:
      continue
  ```

### 예외 처리 ★

#### 기본 `try except`

- `try` 절 실행되고 예외가 발생하지 않으면 `except` 없이 실행이 종료된다.

- 예외가 중간에 발생하면 남은 부분을 수행하지 않고 `except`가 실행된다.

```python
# 활용법
try:
    codeblock1
except 예외:
    codeblock2
```

```python
# 예제
def calc(num1, num2):
    try:
    a = num1 + num2
    b = num1 - num2
    c = num1 * num2
    d = num1 / num2
        return (a, b, c, d)
    except ValueError:
        return '0으로는 나눌 수 업습니다.'

print(calc(5,6))
```

```python
# 예제 2
keys = ['apple', 'apple','banana', 'banana', 'coconut', 'coconut']
my_dict = {}
for key in keys:
    try:
        my_dict[key] += 1
    except KeyError:
        my_dict[key] = 1
print(my_dict) # {'apple': 2, 'banana': 2, 'coconut': 2}
```

#### 복수의 예외 처리

```python
# 활용법
try:
    codeblock1
except (예외1, 예외2):
    codeblock2
    
try:
    codeblock1
except 예외1:
    codeblock2
except 예외2:
    codeblock3
```

```python
# 예제
try:
    num = input(' 100으로 나눌 값을 입력하시오 : ')
    print(100/int(num))
except ZeroDivisionError:
    print('숫자를 넣어줘')
except ValueError:
    print('0 으로 나눌 수 없다.')
except:
    print('모르겠지만 에러야')
```

- 에러가 순차적으로 수행하여 가장 작은 범주부터 시작해야 한다.

#### 에러 문구 처리

에러 문구를 함께 넘겨줄 수 있다.

```python
# 활용법
try:
    codeblock1
except 예외 as err:
    codeblock2
```

```python
# 예제
try:
    empty_list = []
    print(empty_list[-1])
except IndexError as err:
    print(f'{err}, 해당 오류가 발생했어요.') # list index out of range, 해당 오류가 발생했어요.
# print(type(err)) # <class 'IndexError'>
# print(err.args) # ('list index out of range',)

# 예제 2
try:
    ...
except KeyError:
    pass # 오류 회피하기
```

#### `else`

- 에러가 발생하지 않는 경우 수행되는 문장은 `else`를 이용한다.

- 모든 except 절 뒤에와야 한다.

- try 절이 예외를 일으키지 않을 때 실행되어야만 하는 코드에 적절하다.

```python
# 활용법

try:
    codeblock1
except 예외:
    codeblock2
else:
    codeblock3
```

#### `finally`

- 반드시 수행해야하는 문장은 `finally`를 활용한다.
- 예외의 발생 여부와 관계없이 try문을 떠날 때 항상 실행한다.

```python
# 활용법
try:
    codeblock1
except 예외:
    codeblock2
finally:
    codeblock3
```

### 예외 발생시키기

`raise` 를 통해 예외를 강제로 발생시킬 수 있다.

```python
# 예제
try:
    raise ValueError('hi')
except ValueError:
    print('wow!!!') # wow!!!
```

```python
# 예제 2
def my_div(num1, num2):
    try:
        result = num1 / num2
    except ZeroDivisionError as err:
        return f'{err} 오류가 발생하였습니다.'
    except TypeError:
        raise ValueError('숫자를 넣어주세요')
    else:
        return result
```

### `assert`

`assert` 문은 예외를 발생시키는 다른 방법이다.

보통 상태를 검증하는데 사용되며 무조건 `AssertionError`가 발생한다.

```python
# 활용법
assert Boolean expression, error message

# 예제
assert type(1) == int, '문자열을 입력하였습니다.'
```

- 검증식이 거짓일 경우 발생
  - `raise` : 항상 예외 발생
  - `assert` : 지정된 예외에서 발생